version: '2'
services:
    rfbloyalty-app:
        image: rfbloyalty
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rfbloyalty-mysql:3306/rfbloyalty?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rfbloyalty-mysql:
        extends:
            file: mysql.yml
            service: rfbloyalty-mysql
